
export let BountyAddress;
export let BountyAbi;
BountyAddress = "NULL"
BountyAbi = [ { constant: false,
    inputs: [ { name: 'amount', type: 'uint256' } ],
    name: 'withdraw',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function' },
  { constant: false,
    inputs: [ { name: 'submitter', type: 'address' } ],
    name: 'acceptVuln',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function' },
  { constant: true,
    inputs: [],
    name: 'ownerInfo',
    outputs:
     [ { name: '', type: 'uint256' },
       { name: '', type: 'address' },
       { name: '', type: 'string' } ],
    payable: false,
    stateMutability: 'view',
    type: 'function' },
  { constant: true,
    inputs: [ { name: '', type: 'address' } ],
    name: 'mappingAddressToStruct',
    outputs:
     [ { name: 'index', type: 'uint256' },
       { name: 'submitter', type: 'address' },
       { name: 'stage', type: 'bytes1' },
       { name: 'CCVE', type: 'bytes4' },
       { name: 'ipfsSubmission', type: 'bytes' },
       { name: 'lastActionVia', type: 'address' } ],
    payable: false,
    stateMutability: 'view',
    type: 'function' },
  { constant: true,
    inputs: [],
    name: 'getvalue',
    outputs: [ { name: '', type: 'uint256' } ],
    payable: false,
    stateMutability: 'view',
    type: 'function' },
  { constant: true,
    inputs: [],
    name: 'arraylength',
    outputs: [ { name: '', type: 'uint256' } ],
    payable: false,
    stateMutability: 'view',
    type: 'function' },
  { constant: false,
    inputs:
     [ { name: 'CCVE', type: 'bytes4' },
       { name: 'ipfsSubmission', type: 'bytes' } ],
    name: 'submitVuln',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function' },
  { constant: true,
    inputs: [],
    name: 'checkForCurrentSubmit',
    outputs: [ { name: '', type: 'bool' } ],
    payable: false,
    stateMutability: 'view',
    type: 'function' },
  { constant: true,
    inputs: [ { name: '', type: 'uint256' } ],
    name: 'SubmissionArray',
    outputs: [ { name: '', type: 'address' } ],
    payable: false,
    stateMutability: 'view',
    type: 'function' },
  { constant: false,
    inputs: [],
    name: 'deposit',
    outputs: [],
    payable: true,
    stateMutability: 'payable',
    type: 'function' },
  { inputs:
     [ { name: '_index', type: 'uint256' },
       { name: '_sender', type: 'address' },
       { name: '_ipfs', type: 'string' } ],
    payable: true,
    stateMutability: 'payable',
    type: 'constructor' } ]
    